package graft.cpg;

import java.util.function.Consumer;

import com.github.javaparser.ast.Node;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import graft.cpg.context.AstWalkContext;
import graft.cpg.context.ContextStack;


/**
 * The AstWalker walks through the AST generated by the parser in a depth-first fashion, applying
 * the AstNodeVisitor to each node.
 *
 * @author Wim Keirsgieter
 */
public class AstWalker implements Consumer<Node> {

    private static Logger log = LoggerFactory.getLogger(AstWalker.class);

    private ContextStack contextStack;

    public AstWalker() {
        contextStack = new ContextStack();
        contextStack.pushNewContext(new AstWalkContext());
    }

    /**
     * Step into an AST node and apply the AstNodeVisitor to it.
     *
     * @param node the AST node being visited
     */
    @Override
    public void accept(Node node) {
        node.removeComment();
        contextStack = node.accept(new AstNodeVisitor(), contextStack);
    }

}
