package graft;

import java.util.ArrayList;
import java.util.List;

import graft.phases.PhaseResult;

/**
 * The result of a Graft run.
 *
 * This result is a consolidation of the various phase results generated by the phases registered
 * to a given Graft run.
 */
public class GraftResult {

    private List<PhaseResult> phaseResults;

    GraftResult() {
        phaseResults = new ArrayList<>();
    }

    public void addPhaseResult(PhaseResult result) {
        phaseResults.add(result);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        for (PhaseResult result : phaseResults) {
            sb.append(result.toString());
        }
        return sb.toString();
    }

}
